version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
  proxy:
    image: nginx
    volumes:
      - ${PWD}/proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8888:80"
    